// Offline real UI/HTTP/Session/Store, simulated disposable local/cloud compute.
import {chromium} from 'playwright';
import {spawn,spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const docker=(...args)=>{const r=spawnSync('docker',args,{encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
const name='daimon-environments-'+randomUUID(),volume=name+'-data';
const child=spawn('docker',['run','--rm','--pull','never','--name',name,'-p','127.0.0.1::3001','--mount',`type=bind,source=${resolve('..')},target=/workspace,readonly`,'--mount',`type=volume,source=${volume},target=/fixture`,'--mount','type=volume,source=daimon-phase16-go-cache,target=/root/.cache/go-build','-w','/workspace','--env','ENVIRONMENT_SMOKE=1','--env','GOPROXY=off','--env','GOTOOLCHAIN=local','golang:1.27.1','sh','-ec','go build -tags approvalsmoke -buildvcs=false -o /tmp/approval-fixture ./ui/scripts/approval-fixture\nexec /tmp/approval-fixture'],{stdio:['ignore','pipe','pipe']});
let output='',errors='',browser,exited=false;child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>errors+=b);const exit=new Promise(resolve=>child.once('exit',code=>{exited=true;resolve(code);}));
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('fixture timeout '+errors)),180000);const check=()=>{if(output.includes('READY')){clearTimeout(timer);child.stdout.off('data',check);resolve();}};child.stdout.on('data',check);void exit.then(code=>{clearTimeout(timer);reject(new Error('fixture exit '+code+' '+errors));});check();});
 const base='http://'+docker('port',name,'3001/tcp')+'/';browser=await chromium.launch({headless:true,...(process.env.DAIMON_SMOKE_CHANNEL?{channel:process.env.DAIMON_SMOKE_CHANNEL}:{})});const page=await browser.newPage(),pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
 const post=async(path,body,method='POST')=>page.request.fetch(base+'api/v1/'+path,{method,data:body,headers:{Origin:new URL(base).origin}});
 const bot={id:'env-bot',name:'Environment Bot',instructions:'Offline fixture',provider_id:'fixture',model:'fixture',tools:[],permission_mode:'ask',sandbox_profile:{backend:'cua-local',placement:'local',image:'linux',runtime:'gvisor',browser:false,resources:'small',network:'outbound'}};
 assert.equal((await post('bots',bot)).status(),201);const now=new Date().toISOString();assert.equal((await post('threads',{id:'env-thread',bot_id:bot.id,workspace:'/fixture/workspace',title:'Environment Thread',created_at:now,updated_at:now})).status(),201);
 await page.goto(base+'#thread=env-thread');await page.getByRole('tab',{name:'Arquivos',exact:true}).click();await page.getByRole('button',{name:"Ativar ambiente",exact:true}).click();await page.getByText("Revisão 0 · 0 arquivos · 0 bytes").waitFor();
 const env=async()=> (await(await page.request.get(base+'api/v1/threads/env-thread/environment')).json());
 const run=async(message)=>{const id='session-'+randomUUID();assert.equal((await post('sessions',{id,thread_id:'env-thread',message})).status(),202);for(let i=0;i<200;i++){const s=await(await page.request.get(base+'api/v1/sessions/'+id)).json();if(['completed','failed','aborted'].includes(s.status))return s;await new Promise(r=>setTimeout(r,30));}assert.fail('Session timeout');};
 assert.equal((await run('Environment add A')).status,'completed');assert.equal((await env()).revision,1);
 bot.sandbox_profile.backend='cua-cloud';bot.sandbox_profile.placement='cloud';assert.equal((await post('bots/'+bot.id,bot,'PUT')).status(),200);assert.equal((await run('Environment add B')).status,'completed');assert.equal((await env()).revision,2);
 bot.sandbox_profile.backend='cua-local';bot.sandbox_profile.placement='local';assert.equal((await post('bots/'+bot.id,bot,'PUT')).status(),200);assert.equal((await run('Environment check')).status,'completed');assert.equal((await env()).revision,3);
 for(const message of ['Environment fail','Environment sync fail']){assert.equal((await run(message)).status,'failed');assert.equal((await env()).revision,3);}
 const abortID='session-'+randomUUID();assert.equal((await post('sessions',{id:abortID,thread_id:'env-thread',message:'Environment abort'})).status(),202);await new Promise(r=>setTimeout(r,100));assert.equal((await page.request.fetch(base+'api/v1/threads/env-thread/environment',{method:'DELETE',headers:{Origin:new URL(base).origin}})).status(),409);assert.equal((await post('sessions/'+abortID+'/abort',undefined)).status(),202);
 for(let i=0;i<100;i++){const s=await(await page.request.get(base+'api/v1/sessions/'+abortID)).json();if(s.status==='aborted')break;if(i===99)assert.fail('abort timeout');await new Promise(r=>setTimeout(r,30));}assert.equal((await env()).revision,3);
 await page.reload();await page.getByText("Revisão 3 · 2 arquivos · 12 bytes").waitFor();assert.equal((await page.request.fetch(base+'api/v1/threads/env-thread',{method:'DELETE',headers:{Origin:new URL(base).origin}})).status(),409);
 // Restart the application process inside the fixture container; durable volume
 // remains, every Session/guest is already terminal and cleaned.
 docker('exec',name,'kill','-TERM','1');assert.equal(await exit,0,errors);
 const restart=spawn('docker',['run','--rm','--pull','never','--name',name+'-restart','-p','127.0.0.1::3001','--mount',`type=bind,source=${resolve('..')},target=/workspace,readonly`,'--mount',`type=volume,source=${volume},target=/fixture`,'--mount','type=volume,source=daimon-phase16-go-cache,target=/root/.cache/go-build','-w','/workspace','--env','ENVIRONMENT_SMOKE=1','--env','GOPROXY=off','golang:1.27.1','sh','-ec','go build -tags approvalsmoke -buildvcs=false -o /tmp/approval-fixture ./ui/scripts/approval-fixture\nexec /tmp/approval-fixture'],{stdio:['ignore','pipe','pipe']});
 let ready='';restart.stdout.on('data',b=>ready+=b);restart.stderr.on('data',b=>errors+=b);const restartedExit=new Promise(resolve=>restart.once('exit',resolve));try{for(let i=0;i<300&&!ready.includes('READY');i++)await new Promise(r=>setTimeout(r,100));assert.ok(ready.includes('READY'),errors);const restartedBase='http://'+docker('port',name+'-restart','3001/tcp')+'/';await page.goto(restartedBase+'#thread=env-thread');await page.getByRole('tab',{name:'Arquivos',exact:true}).click();await page.getByText("Revisão 3 · 2 arquivos · 12 bytes").waitFor();await page.getByRole('button',{name:"Excluir ambiente",exact:true}).click();await page.getByRole('button',{name:"Confirmar exclusão do ambiente",exact:true}).click();await page.getByRole('button',{name:"Ativar ambiente",exact:true}).waitFor();docker('stop','--time','10',name+'-restart');assert.equal(await restartedExit,0,errors);}finally{spawnSync('docker',['stop','--time','10',name+'-restart'],{timeout:30000});}
 const catalog=JSON.parse(docker('run','--rm','--mount',`type=volume,source=${volume},target=/fixture,readonly`,'golang:1.27.1','cat','/fixture/sandboxes.json'));assert.ok(catalog.records.every(s=>s.info.cleanup==='complete'));
 assert.deepEqual(pageErrors,[]);console.log('Environment smoke passed: explicit enable, local A -> cloud A+B -> local, failed/aborted sync preservation, busy deletion, restart and confirmed deletion.');
}finally{await browser?.close();if(!exited){spawnSync('docker',['stop','--time','10',name],{timeout:30000});await exit;}spawnSync('docker',['volume','rm',volume],{timeout:30000});}
