import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {EnvironmentPanel} from './EnvironmentPanel';
import {APIError,environmentsAPI} from '../api/client';
const metadata={version:1 as const,id:'env-'+'a'.repeat(24),thread_id:'thread',revision:2,files:1,directories:0,bytes:3,manifest_hash:'b'.repeat(64),created_at:'2026-10-08T00:00:00Z',updated_at:'2026-10-08T00:00:00Z'};
beforeEach(()=>{Object.defineProperties(HTMLDialogElement.prototype,{showModal:{configurable:true,value:function(){this.setAttribute('open','')}},close:{configurable:true,value:function(){this.removeAttribute('open')}}});});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
describe('persistent Environment',()=>{
 it('enables only explicitly and confirms deletion',async()=>{vi.spyOn(environmentsAPI,'get').mockRejectedValue(new APIError('environment_not_found'));const create=vi.spyOn(environmentsAPI,'create').mockResolvedValue(metadata);const remove=vi.spyOn(environmentsAPI,'remove').mockResolvedValue();render(<EnvironmentPanel threadID="thread" active={false} sandboxEnabled cloud={false}/>);await waitFor(()=>expect((screen.getByText("Ativar ambiente") as HTMLButtonElement).disabled).toBe(false));expect(create).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Ativar ambiente"));await screen.findByText('Revisão 2 · 1 arquivos · 3 bytes');fireEvent.click(screen.getByText("Excluir ambiente"));expect(remove).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Confirmar exclusão do ambiente"));await waitFor(()=>expect(remove).toHaveBeenCalledWith('thread'));});
 it('blocks deletion during Session and displays saving cost',async()=>{vi.spyOn(environmentsAPI,'get').mockResolvedValue(metadata);render(<EnvironmentPanel threadID="thread" active sandboxEnabled cloud snapshot={{id:'run',thread_id:'thread',status:'running',started_at:metadata.created_at,finished_at:null,last_event_sequence:1,stop_reason:'',error_category:'',steps:1,tool_calls:0,truncated_tool_results:0,persistent_workspace:{id:metadata.id,starting_revision:2,committed_revision:0,committed:false,state:'saving'}}}/>);await screen.findByText("Excluir ambiente");expect((screen.getByText("Excluir ambiente") as HTMLButtonElement).disabled).toBe(true);expect(screen.getByText(/Salvando arquivos antes de liberar o computador na nuvem/)).toBeTruthy();});
 it('shows safe storage failures and no implicit import',async()=>{vi.spyOn(environmentsAPI,'get').mockRejectedValue(new APIError('environment_unavailable'));render(<EnvironmentPanel threadID="thread" active={false} sandboxEnabled cloud={false}/>);await screen.findByRole('alert');expect(screen.getByText(/pasta local não é importada/)).toBeTruthy();expect((screen.getByText("Ativar ambiente") as HTMLButtonElement).disabled).toBe(true);});
});
