import { copy } from '../i18n/copy';
import {useEffect,useState} from 'react';
import {APIError,environmentsAPI,safeError} from '../api/client';
import type {PersistentEnvironment,SessionSnapshot} from '../api/types';
import {label} from '../i18n/pt-BR';
import {Modal} from './Editors';

export function EnvironmentPanel({threadID,active,sandboxEnabled,snapshot,cloud,onNotice}:{threadID:string;active:boolean;sandboxEnabled:boolean;snapshot?:SessionSnapshot;cloud:boolean;onNotice?:(message:string)=>void}){
 const [environment,setEnvironment]=useState<PersistentEnvironment>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[refresh,setRefresh]=useState(0);
 const phase=snapshot?.thread_id===threadID?snapshot.persistent_workspace:undefined;
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');void environmentsAPI.get(threadID,controller.signal).then(v=>{if(!controller.signal.aborted)setEnvironment(v);}).catch(e=>{if(!controller.signal.aborted){if(e instanceof APIError&&e.code==='environment_not_found')setEnvironment(undefined);else setError(safeError(e));}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[threadID,refresh,snapshot?.id,snapshot?.status,phase?.state]);
 const enable=async()=>{setBusy(true);setError('');try{setEnvironment(await environmentsAPI.create(threadID));onNotice?.(copy["Ambiente ativado"]);}catch(e){setError(safeError(e));}finally{setBusy(false);}};
 const remove=async()=>{setBusy(true);setError('');try{await environmentsAPI.remove(threadID);setEnvironment(undefined);setConfirm(false);}catch(e){setError(safeError(e));}finally{setBusy(false);}};
 return <aside className="environment-surface" aria-label={copy["Persistent Environment"]}><strong>{copy["Persistent Environment"]}</strong><p className="hint">{copy["Local plaintext workspace revisions, separate from disposable compute. No host workspace import. File content is not automatically sent to the model or Memory."]}</p>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">{copy["Loading Environment…"]}</p>}{environment?<><p>{copy["Revisão"]}{' '}{environment.revision} · {environment.files} {copy["arquivos ·"]}{' '}{environment.bytes} {copy["bytes"]}</p><time dateTime={environment.updated_at}>{new Date(environment.updated_at).toLocaleString('pt-BR')}</time>{!sandboxEnabled&&<p role="alert">{copy["Select Local or Cloud Sandbox on the Bot before running this Thread."]}</p>}<button disabled={active||busy||loading} onClick={()=>setConfirm(true)}>{copy["Delete Environment"]}</button></>:<button disabled={active||busy||loading||!sandboxEnabled||!!error} onClick={()=>void enable()}>{copy["Enable empty Environment"]}</button>}{phase&&<p role="status">{copy["Workspace:"]}{' '}{label(phase.state)}{phase.committed?` · revisão confirmada ${phase.committed_revision}`:''}</p>}{cloud&&phase?.state==='saving'&&<p className="notice">{copy["Saving workspace before releasing paid cloud compute. Transfer is bounded to 60 seconds."]}</p>}{confirm&&<Modal title={copy["Delete persistent Environment"]} onClose={()=>{if(!busy)setConfirm(false);}}><p>{copy["Delete all durable workspace files for this Thread? This cannot be undone. Conversation history and Memory remain separate."]}</p>{error&&<p role="alert">{error}</p>}<footer><button disabled={busy} onClick={()=>setConfirm(false)}>{copy["Cancel"]}</button><button className="danger-text" disabled={active||busy} onClick={()=>void remove()}>{busy?copy["Deleting…"]:copy["Confirm Environment deletion"]}</button></footer></Modal>}</aside>;
}
