import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {MemoryPanel} from './MemoryPanel';
import {api} from '../api/client';
import type {MemoryRecord} from '../api/types';
const record:MemoryRecord={id:'memory-a',scope:'global',scope_id:'',kind:'note',content:'<script>chosen content</script>',tags:['coding'],created_at:'2026-10-07T12:00:00Z',updated_at:'2026-10-07T12:00:00Z',provenance:{source_type:'manual'}};
beforeEach(()=>{Object.defineProperties(HTMLDialogElement.prototype,{showModal:{configurable:true,value:function(){this.setAttribute('open','')}},close:{configurable:true,value:function(){this.removeAttribute('open')}}});vi.spyOn(api,'memories').mockResolvedValue([record])});
afterEach(()=>{cleanup();vi.restoreAllMocks()});
const panel=()=>render(<MemoryPanel bots={[]} threads={[]} onClose={()=>{}}/>);
it('shows deliberately saved content safely and all scopes with manual provenance',async()=>{panel();await screen.findByText(record.content);expect(document.querySelector('script')).toBeNull();expect(screen.getByText(/texto local/)).toBeTruthy();expect(screen.getByText(/coding · salva por você/)).toBeTruthy()});
it('requires explicit scope/kind and creates exact content without forged metadata',async()=>{
 const save=vi.spyOn(api,'saveMemory').mockResolvedValue(record);panel();await screen.findByText(record.content);fireEvent.click(screen.getByText("Nova memória"));
 expect((screen.getByLabelText("Onde usar esta memória") as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText("Tipo de memória") as HTMLSelectElement).value).toBe('');
 fireEvent.change(screen.getByLabelText("Onde usar esta memória"),{target:{value:'global'}});fireEvent.change(screen.getByLabelText("Tipo de memória"),{target:{value:'preference'}});fireEvent.change(screen.getByLabelText("Conteúdo da memória"),{target:{value:'  exact chosen text  '}});fireEvent.change(screen.getByLabelText("Marcadores"),{target:{value:'coding, personal'}});fireEvent.click(screen.getByText("Salvar memória"));
 await waitFor(()=>expect(save).toHaveBeenCalled());const input=save.mock.calls[0][0];expect(input).toEqual({id:expect.stringMatching(/^memory-/),scope:'global',scope_id:'',kind:'preference',content:'  exact chosen text  ',tags:['coding','personal']});expect(input).not.toHaveProperty('created_at');await waitFor(()=>expect(api.memories).toHaveBeenCalledTimes(2))
});
it('keeps scope immutable while editing and refreshes accepted content',async()=>{const save=vi.spyOn(api,'saveMemory').mockResolvedValue({...record,content:'updated'});panel();await screen.findByText(record.content);fireEvent.click(screen.getByLabelText('Editar memória'));expect((screen.getByLabelText("Onde usar esta memória") as HTMLSelectElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText("Conteúdo da memória"),{target:{value:'updated'}});fireEvent.click(screen.getByText("Salvar memória"));await waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({id:'memory-a',scope:'global',content:'updated'}),true))});
it('requires a separate deletion confirmation and retains records on error',async()=>{const remove=vi.spyOn(api,'deleteMemory').mockRejectedValue(new Error('private failure'));panel();await screen.findByText(record.content);fireEvent.click(screen.getByLabelText('Excluir memória'));expect(remove).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Confirmar exclusão da memória"));await screen.findByRole('alert');expect(screen.getByText(record.content)).toBeTruthy();expect(screen.queryByText('private failure')).toBeNull()});
it('deletes explicitly and reloads persistent data on reopening',async()=>{const remove=vi.spyOn(api,'deleteMemory').mockResolvedValue(undefined);const view=panel();await screen.findByText(record.content);fireEvent.click(screen.getByLabelText('Excluir memória'));fireEvent.click(screen.getByText("Confirmar exclusão da memória"));await waitFor(()=>expect(remove).toHaveBeenCalledWith('memory-a'));await waitFor(()=>expect(api.memories).toHaveBeenCalledTimes(2));view.unmount();panel();await screen.findByText(record.content);expect(api.memories).toHaveBeenCalledTimes(3)});
it('rejects repeated tags and cancels without saving',async()=>{const save=vi.spyOn(api,'saveMemory').mockResolvedValue(record);panel();await screen.findByText(record.content);fireEvent.click(screen.getByLabelText('Editar memória'));fireEvent.change(screen.getByLabelText("Marcadores"),{target:{value:'coding, coding'}});fireEvent.click(screen.getByText("Salvar memória"));await screen.findByRole('alert');expect(save).not.toHaveBeenCalled();fireEvent.click(screen.getByText("Cancelar edição da memória"));expect(screen.getByText(record.content)).toBeTruthy()});
