import { copy } from '../i18n/copy';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import {pt,label} from '../i18n/pt-BR';
import {api,safeError} from '../api/client';
import {bytes,newID,type Bot,type Thread,type MemoryRecord,type MemoryScope,type MemoryKind} from '../api/types';
import {Modal,ErrorMessage} from './Editors';

function MemoryForm({record,bots,threads,onSave,onCancel}:{record?:MemoryRecord;bots:Bot[];threads:Thread[];onSave:()=>void;onCancel:()=>void}){
 const [scope,setScope]=useState<MemoryScope|''>(record?.scope??''),[scopeID,setScopeID]=useState(record?.scope_id??''),[kind,setKind]=useState<MemoryKind|''>(record?.kind??''),[content,setContent]=useState(record?.content??''),[tags,setTags]=useState(record?.tags.join(', ')??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const choices=scope==='bot'?bots.map(b=>({id:b.id,label:b.name})):threads.map(t=>({id:t.id,label:t.title||pt.unnamed}));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;const list=tags.trim()?tags.split(',').map(t=>t.trim()):[];
 if(!scope||!kind||!content.trim()||bytes(content)>16384||(scope!=='global'&&!scopeID)||list.length>16||new Set(list).size!==list.length||list.some(t=>!/^[a-z][a-z0-9_-]{0,63}$/.test(t))){setError(copy["Choose scope and kind, nonblank content up to 16 KiB, and up to 16 distinct lowercase tags."]);return}
 setBusy(true);setError('');try{await api.saveMemory({id:record?.id??newID('memory'),scope,scope_id:scope==='global'?'':scopeID,kind,content,tags:list},!!record);onSave()}catch(e){setError(safeError(e))}finally{setBusy(false)}};
 return <form onSubmit={e=>void submit(e)}><h3>{record?copy["Edit Memory"]:copy["Create Memory"]}</h3><label>{copy["Memory scope"]}<select required disabled={!!record} value={scope} onChange={e=>{setScope(e.target.value as MemoryScope|'');setScopeID('')}}><option value="">{copy["Choose scope"]}</option><option value="global">{label("global")}</option><option value="bot">{label("bot")}</option><option value="thread">{label("thread")}</option></select></label>{scope&&scope!=='global'&&<label>{copy["Scope target"]}<select required disabled={!!record} value={scopeID} onChange={e=>setScopeID(e.target.value)}><option value="">{copy["Choose target"]}</option>{scopeID&&!choices.some(c=>c.id===scopeID)&&<option value={scopeID}>{copy["Recurso indisponível"]}</option>}{choices.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>}<label>{copy["Memory kind"]}<select required value={kind} onChange={e=>setKind(e.target.value as MemoryKind|'')}><option value="">{copy["Choose kind"]}</option>{['fact','preference','instruction','note'].map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label><label>{copy["Memory content"]}<textarea required rows={6} value={content} onChange={e=>setContent(e.target.value)}/></label><label>{copy["Memory tags"]}<input value={tags} onChange={e=>setTags(e.target.value)} placeholder={copy["Comma-separated lowercase tags"]}/></label><p className="hint">{copy["Scope stays fixed. Timestamps and manual provenance are owned by the server."]}</p><ErrorMessage message={error}/><footer><button type="button" disabled={busy} onClick={onCancel}>{copy["Cancel Memory edit"]}</button><button className="primary" disabled={busy}>{busy?copy["Saving Memory..."]:copy["Save Memory"]}</button></footer></form>;
}
export function MemoryPanel({bots,threads,onClose,inline=false,threadID,botID,onNotice}:{bots:Bot[];threads:Thread[];onClose:()=>void;inline?:boolean;threadID?:string;botID?:string;onNotice?:(message:string)=>void}){
 const [items,setItems]=useState<MemoryRecord[]>([]),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState<MemoryRecord|'create'>(),[deleting,setDeleting]=useState<MemoryRecord>(),[busy,setBusy]=useState(false),[scope,setScope]=useState('all');
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');void api.memories(c.signal).then(v=>{if(!c.signal.aborted)setItems(v)}).catch(e=>{if(!c.signal.aborted)setError(safeError(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[revision]);
 const remove=async()=>{if(!deleting||busy)return;setBusy(true);setError('');try{await api.deleteMemory(deleting.id);setDeleting(undefined);setRevision(r=>r+1)}catch(e){setError(safeError(e))}finally{setBusy(false)}};
 const surface=(children:ReactNode)=>inline?<section className="memory-surface"><h2>{pt.memory}</h2>{children}</section>:<Modal title={pt.memory} onClose={()=>{if(!busy)onClose()}}>{children}</Modal>;
 return surface(<><p className="notice">{copy["Local plaintext. Save only what you explicitly choose. Selected memories are sent to the configured provider on future turns; they never grant tool permissions."]}</p>{editor?<MemoryForm key={editor==='create'?'create':editor.id} record={editor==='create'?undefined:editor} bots={bots} threads={threads} onCancel={()=>setEditor(undefined)} onSave={()=>{setEditor(undefined);setRevision(r=>r+1);onNotice?.(copy["Memória salva"]);}}/>:<><div className="memory-actions"><button onClick={()=>setEditor('create')}>{copy["Create Memory"]}</button></div><label>{copy["Filter Memory scope"]}<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">{copy["All scopes"]}</option>{['global','bot','thread'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><ErrorMessage message={deleting?undefined:error}/>{loading&&<p role="status">{copy["Loading Memory..."]}</p>}{!loading&&items.length===0&&<p>{copy["No memories saved."]}</p>}<ul className="memory-list">{(['thread','bot','global'] as const).filter(group=>scope==='all'||scope===group).map(group=><li className="memory-group" key={group}><h3>{group==='thread'?copy["Memórias das conversas"]:group==='bot'?copy["Memórias dos bots"]:copy["Memórias globais"]}</h3><ul>{items.filter(m=>m.scope===group).sort((a,b)=>Number(b.scope_id===(group==='thread'?threadID:botID))-Number(a.scope_id===(group==='thread'?threadID:botID))).map(m=><li key={m.id}><h3>{label(m.scope)} · {m.scope==="bot"?bots.find(b=>b.id===m.scope_id)?.name:m.scope==="thread"?threads.find(t=>t.id===m.scope_id)?.title||pt.unnamed:""} · {label(m.kind)}</h3><p className="memory-content">{m.content}</p><p className="hint">{m.tags.join(', ')||copy["No tags"]} {copy["· manual ·"]}{' '}{new Date(m.updated_at).toLocaleString('pt-BR')}</p><div className="memory-actions"><button aria-label={copy["Editar memória"]} onClick={()=>{setDeleting(undefined);setEditor(m)}}>{copy["Edit"]}</button><button aria-label={copy["Excluir memória"]} onClick={()=>setDeleting(m)}>{copy["Delete"]}</button></div></li>)}</ul></li>)}</ul>{deleting&&<Modal title={copy["Delete"]+" memória"} onClose={()=>{if(!busy)setDeleting(undefined);}}><ErrorMessage message={error}/><div className="memory-delete"><p>{copy["Delete this saved Memory permanently? This does not remove conversation messages."]}</p><button disabled={busy} onClick={()=>setDeleting(undefined)}>{copy["Cancel Memory deletion"]}</button><button disabled={busy} className="danger-text" onClick={()=>void remove()}>{copy["Confirm Memory deletion"]}</button></div></Modal>}</>}</>);
}
