import {useEffect,useState} from 'react';
import {request,safeError} from '../api/client';
import {newID,type Thread} from '../api/types';
import {Modal} from './Editors';
import {routinesCopy} from '../i18n/routines';
export type RoutineView={id:string;bot_id:string;thread_id:string;title:string;daily_at:string;timezone:string;enabled:boolean;next_at:string;state:string;session_id?:string};
const labels=routinesCopy.states;
export function decodeRoutines(value:unknown):RoutineView[]{
 if(!value||typeof value!=='object'||!('routines' in value)||!Array.isArray(value.routines)||value.routines.length>32||!('server_only' in value)||value.server_only!==true)throw new Error();
 const seen=new Set<string>();return value.routines.map((v:unknown)=>{if(!v||typeof v!=='object')throw new Error();const r=v as RoutineView;if(!['id','bot_id','thread_id','title','daily_at','timezone','next_at','state'].every(k=>typeof (v as Record<string,unknown>)[k]==='string')||typeof r.enabled!=='boolean'||!Number.isFinite(Date.parse(r.next_at))||!Object.hasOwn(labels,r.state)||seen.has(r.id)||(r.session_id!==undefined&&typeof r.session_id!=='string'))throw new Error();seen.add(r.id);return r;});
}
export function RoutinePanel({botID,threads,onOpen}:{botID?:string;threads:Thread[];onOpen:(threadID:string,sessionID:string)=>void}){
 const[items,setItems]=useState<RoutineView[]>([]),[error,setError]=useState(''),[title,setTitle]=useState(''),[prompt,setPrompt]=useState(''),[daily,setDaily]=useState('09:00'),[zone,setZone]=useState('America/Sao_Paulo'),[thread,setThread]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[remove,setRemove]=useState<RoutineView>();
 useEffect(()=>{const controller=new AbortController();const load=()=>{void request('/routines','GET',undefined,controller.signal).then(decodeRoutines).then(v=>{if(!controller.signal.aborted){setItems(v);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(safeError(e));});};load();const timer=setInterval(load,5000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
 const mutate=async(path:string,method:string,body?:unknown)=>{setBusy(true);setError('');try{await request(path,method,body);setRefresh(n=>n+1);return true;}catch(e){setError(safeError(e));return false;}finally{setBusy(false);}};
 const create=async()=>{if(!botID)return;const ok=await mutate('/routines','POST',{id:newID('routine'),bot_id:botID,thread_id:thread,title,prompt,daily_at:daily,timezone:zone,enabled:true});if(ok){setTitle('');setPrompt('');}};
 return <section className="feature-surface" aria-label="Rotinas"><h3>{routinesCopy.title}</h3><p className="hint">{routinesCopy.serverOnly}</p>{error&&<p role="alert">{error}</p>}
 {items.filter(r=>r.bot_id===botID).map(r=><article key={r.id}><strong>{r.title}</strong><p role="status">{labels[r.state]} · {r.daily_at} · {r.timezone}</p><p>Próximo horário: {new Date(r.next_at).toLocaleString('pt-BR')}</p><button disabled={busy} onClick={()=>void mutate(`/routines/${encodeURIComponent(r.id)}`,'PUT',{enabled:!r.enabled})}>{r.enabled?'Pausar rotina':'Ativar rotina'}</button><button disabled={busy} onClick={()=>setRemove(r)}>Excluir rotina</button>{r.session_id&&<button onClick={()=>onOpen(r.thread_id,r.session_id!)}>Abrir execução</button>}</article>)}
 {botID&&<details><summary>Nova rotina diária</summary><form onSubmit={e=>{e.preventDefault();void create();}}><label>Título da rotina<input required maxLength={256} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Conversa da rotina<select aria-label="Conversa da rotina" required value={thread} onChange={e=>setThread(e.target.value)}><option value="">Selecione uma conversa</option>{threads.filter(t=>t.bot_id===botID).map(t=><option key={t.id} value={t.id}>{t.title||'Conversa sem título'}</option>)}</select></label><label>Tarefa da rotina<textarea required value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>Horário diário<input required type="time" value={daily} onChange={e=>setDaily(e.target.value)}/></label><label>Fuso horário<input required value={zone} onChange={e=>setZone(e.target.value)}/></label><p className="hint">{routinesCopy.limits}</p><button disabled={busy}>Criar rotina</button></form></details>}
 {remove&&<Modal title="Excluir rotina" onClose={()=>{if(!busy)setRemove(undefined);}}><p>Excluir {remove.title}? A execução e suas aprovações existentes continuam independentes.</p><button disabled={busy} onClick={()=>setRemove(undefined)}>Cancelar</button><button disabled={busy} onClick={()=>{void mutate(`/routines/${encodeURIComponent(remove.id)}`,'DELETE').then(ok=>{if(ok)setRemove(undefined);});}}>Confirmar exclusão da rotina</button></Modal>}</section>;
}
